image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64
  - npm --add-python-to-path='true' --vs2017 --debug install --global --production windows-build-tools
  - npm install

build_script:
  - npm run dist
