image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64
  - npm install
  - npm install electron-builder -g

build_script:
  - electron-builder -mwl
  - type C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2020-08-07T22_46_55_179Z-debug.log
